import {
    AlignLeft,
    ArrowUpRight,
    Calendar,
    CalendarClock,
    CalendarPlus,
    CircleChevronDown,
    DollarSign,
    Globe,
    Hash,
    Link2,
    ListChecks,
    Mail,
    Paperclip,
    Percent,
    Phone,
    Sigma,
    SquareCheck,
    SquareFunction,
    Star,
    Type,
    User,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { FieldType } from './types';

export const FIELD_ICONS: Record<FieldType, LucideIcon> = {
    text: Type,
    longText: AlignLeft,
    number: Hash,
    currency: DollarSign,
    percent: Percent,
    checkbox: SquareCheck,
    date: Calendar,
    select: CircleChevronDown,
    multiSelect: ListChecks,
    user: User,
    link: Link2,
    attachment: Paperclip,
    rating: Star,
    url: Globe,
    email: Mail,
    phone: Phone,
    formula: SquareFunction,
    lookup: ArrowUpRight,
    rollup: Sigma,
    count: Hash,
    createdAt: CalendarPlus,
    updatedAt: CalendarClock,
};
